FROM alpine:3.2

ENV OPENSSL_VERSION 1.0.2e-r0

RUN apk upgrade --update --available && \
    apk add \
      ca-certificates \
      git \
      "openssl>=${OPENSSL_VERSION}" \
    && adduser -Du 1000 caddy \
    && rm -f /var/cache/apk/*

VOLUME ["/etc/caddy"]
VOLUME ["/home/caddy"]

COPY caddy /usr/sbin/caddy

# Run as an unprivileged user.
USER caddy
ENTRYPOINT ["/usr/sbin/caddy"]
