FROM alpine:3.4

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      -X http://dl-cdn.alpinelinux.org/alpine/edge/main \
      ca-certificates \
      git \
      libressl \
    && adduser -Du 1000 caddy

VOLUME ["/etc/caddy"]
VOLUME ["/home/caddy"]

COPY caddy /usr/sbin/caddy

# Run as an unprivileged user.
USER caddy
ENTRYPOINT ["/usr/sbin/caddy"]
