#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Build the docker image. Invoke as "ci/build".
################################################################################

. ci/functions.sh

cat >ci/vars <<EOF
declare -rx CADDY_VERSION="$(awk -F' ' '/github.com\/mholt\/caddy/ {print $NF}' src/main/go.mod)"
declare -rx BUILD_DATE=$(date +%Y%m%dT%H%M)
declare -rx VCS_REF=$(git rev-parse --short HEAD)
declare -rx TAG=\${CADDY_VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF

. ci/vars

run docker-compose build
