#!/bin/sh
set -e

. src/CADDY_VERSION
cat > ci/vars <<EOF
export CADDY_VERSION=${CADDY_VERSION}
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=\${CADDY_VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF

. ci/vars

git submodule sync
git submodule update --init --recursive

echo
echo Build fixtures for the test harness.
docker rm -f fixtures || :
docker build --rm -t fixtures fixtures/
docker create --name=fixtures fixtures /bin/true

echo
echo Build caddy runtime.
docker-compose build caddy caddy_tag
