#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Build the docker image. Invoke as "ci/build".
################################################################################

. ci/functions.sh

. src/CADDY_VERSION
cat > ci/vars <<EOF
declare -rx CADDY_VERSION=${CADDY_VERSION}
declare -rx BUILD_DATE=$(date +%Y%m%dT%H%M)
declare -rx VCS_REF=$(git rev-parse --short HEAD)
declare -rx TAG=\${CADDY_VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF

. ci/vars

echo
echo Build fixtures for the test harness.
docker rm -f fixtures || :
docker build --rm -t fixtures fixtures/
docker create --name=fixtures fixtures /bin/true

echo
echo Build caddy runtime.
docker-compose build caddy caddy_tag
