#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Clean the local build environment.
################################################################################

. ci/functions.sh

docker-compose down
docker ps -a | grep fixtures && docker rm fixtures
docker images | awk '/caddy/ {print $3}' | xargs docker rmi -f
docker images | awk '/fixtures|builder/ {print $3}' | xargs docker rmi -f
docker images -qf dangling=true | xargs docker rmi
