#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Clean the local build environment.
################################################################################

. ci/functions.sh

run docker-compose down
docker images | awk '/caddy/ {print $3}' | run xargs docker rmi -f
docker images | awk '/builder/ {print $3}' | run xargs docker rmi -f
docker images -qf dangling=true | run xargs docker rmi
