#!/bin/sh
set -e

. ci/vars

touch test/env.bash

echo
echo Copy caddy binary into test area.
docker rm -f copier &> /dev/null || :
docker create --name=copier jumanjiman/caddy /bin/true
docker cp copier:/usr/sbin/caddy test/
docker rm -f copier &> /dev/null || :

echo
echo Start services.
docker-compose up -d caddy1 caddy2
sleep 5

echo
echo Invoke BATS tests.
echo
bats test/*.bats

echo
echo Check every file for things like trailing whitespace.
# Hint: -v1 shows just the names of offending files.
#       -v2 shows lines with trailing whitespace.
ci/check-files -v1
