#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################
. ci/bootstrap
. ci/vars

touch test/env.bash

run pre-commit run --all-files --hook-stage manual

info 'Ensure build is up-to-date.'
ci/build

info 'Copy caddy binary into test area.'
run docker rm -f copier &>/dev/null || :
run docker create --name=copier jumanjiman/caddy /bin/true
run docker cp copier:/usr/sbin/caddy test/
run docker rm -f copier &>/dev/null || :

info 'Start services.'
run docker-compose up -d caddy1 caddy2
run sleep 5

info 'Invoke BATS tests.'
run bats test/*.bats
