#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################
. ci/bootstrap
. ci/vars
. ci/functions.sh

touch test/env.bash

echo
echo Check every file for things like trailing whitespace.
pre-commit run --all-files --verbose

echo
echo Copy caddy binary into test area.
docker rm -f copier &>/dev/null || :
docker create --name=copier jumanjiman/caddy /bin/true
docker cp copier:/usr/sbin/caddy test/
docker rm -f copier &>/dev/null || :

echo
echo Start services.
docker-compose up -d caddy1 caddy2
sleep 5

echo
echo Invoke BATS tests.
echo
bats test/*.bats
